name: Onboarding
on:
  pull_request:
    types:
      - closed
    branches:
      - latest
    paths:
      - .github/workflows/CONTRIBUTING.md

jobs:
  github:
    name: Github organization membership
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_org_token: ${{ secrets.ORG_GITHUB_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@main

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          terraform-version: '1.0.4'

      - name: Initialize modules
        run: terraform init

      - name: Validate syntax
        run: terraform validate

      - name: Execute plan of required operations
        run: terraform plan -input=false

      - name: Perform changes
        if: 'false'
        run: terraform apply -input=false -auto-approve
